/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.jooq.tables.Biometrics;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "biometrics",
    schema = "sample",
    uniqueConstraints = {
        @UniqueConstraint(name = "biometrics_device_id_key", columnNames = { "device_id" }),
        @UniqueConstraint(name = "biometrics_public_key_key", columnNames = { "public_key" })
    },
    indexes = {
        @Index(name = "idx_biometrics_user_id", columnList = "user_id ASC")
    }
)
public class BiometricsRecord extends UpdatableRecordImpl<BiometricsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.biometrics.id</code>.
     */
    public BiometricsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.biometrics.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>sample.biometrics.user_id</code>.
     */
    public BiometricsRecord setUserId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.biometrics.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>sample.biometrics.public_key</code>.
     */
    public BiometricsRecord setPublicKey(byte[] value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sample.biometrics.public_key</code>.
     */
    @Column(name = "public_key", nullable = false)
    public byte[] getPublicKey() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>sample.biometrics.device_id</code>.
     */
    public BiometricsRecord setDeviceId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sample.biometrics.device_id</code>.
     */
    @Column(name = "device_id", nullable = false, length = 255)
    public String getDeviceId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sample.biometrics.last_used_at</code>.
     */
    public BiometricsRecord setLastUsedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sample.biometrics.last_used_at</code>.
     */
    @Column(name = "last_used_at", precision = 6)
    public OffsetDateTime getLastUsedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BiometricsRecord
     */
    public BiometricsRecord() {
        super(Biometrics.BIOMETRICS);
    }

    /**
     * Create a detached, initialised BiometricsRecord
     */
    public BiometricsRecord(UUID id, UUID userId, byte[] publicKey, String deviceId, OffsetDateTime lastUsedAt) {
        super(Biometrics.BIOMETRICS);

        setId(id);
        setUserId(userId);
        setPublicKey(publicKey);
        setDeviceId(deviceId);
        setLastUsedAt(lastUsedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised BiometricsRecord
     */
    public BiometricsRecord(com.doruk.jooq.tables.pojos.Biometrics value) {
        super(Biometrics.BIOMETRICS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setPublicKey(value.getPublicKey());
            setDeviceId(value.getDeviceId());
            setLastUsedAt(value.getLastUsedAt());
            resetTouchedOnNotNull();
        }
    }
}
