/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.jooq.enums.FileVisibility;
import com.doruk.jooq.tables.MediaStore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "media_store",
    schema = "sample",
    uniqueConstraints = {
        @UniqueConstraint(name = "media_store_object_key_key", columnNames = { "object_key" })
    }
)
public class MediaStoreRecord extends UpdatableRecordImpl<MediaStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.media_store.id</code>.
     */
    public MediaStoreRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.media_store.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sample.media_store.object_key</code>.
     */
    public MediaStoreRecord setObjectKey(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.media_store.object_key</code>.
     */
    @Column(name = "object_key", nullable = false)
    public String getObjectKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sample.media_store.visibility</code>.
     */
    public MediaStoreRecord setVisibility(FileVisibility value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sample.media_store.visibility</code>.
     */
    @Column(name = "visibility")
    public FileVisibility getVisibility() {
        return (FileVisibility) get(2);
    }

    /**
     * Setter for <code>sample.media_store.mime_type</code>.
     */
    public MediaStoreRecord setMimeType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sample.media_store.mime_type</code>.
     */
    @Column(name = "mime_type", nullable = false)
    public String getMimeType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sample.media_store.size</code>.
     */
    public MediaStoreRecord setSize(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sample.media_store.size</code>.
     */
    @Column(name = "size", nullable = false)
    public Long getSize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>sample.media_store.created_at</code>.
     */
    public MediaStoreRecord setCreatedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sample.media_store.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>sample.media_store.deleted_at</code>.
     */
    public MediaStoreRecord setDeletedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sample.media_store.deleted_at</code>.
     */
    @Column(name = "deleted_at", precision = 6)
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaStoreRecord
     */
    public MediaStoreRecord() {
        super(MediaStore.MEDIA_STORE);
    }

    /**
     * Create a detached, initialised MediaStoreRecord
     */
    public MediaStoreRecord(Long id, String objectKey, FileVisibility visibility, String mimeType, Long size, OffsetDateTime createdAt, OffsetDateTime deletedAt) {
        super(MediaStore.MEDIA_STORE);

        setId(id);
        setObjectKey(objectKey);
        setVisibility(visibility);
        setMimeType(mimeType);
        setSize(size);
        setCreatedAt(createdAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised MediaStoreRecord
     */
    public MediaStoreRecord(com.doruk.jooq.tables.pojos.MediaStore value) {
        super(MediaStore.MEDIA_STORE);

        if (value != null) {
            setId(value.getId());
            setObjectKey(value.getObjectKey());
            setVisibility(value.getVisibility());
            setMimeType(value.getMimeType());
            setSize(value.getSize());
            setCreatedAt(value.getCreatedAt());
            setDeletedAt(value.getDeletedAt());
            resetTouchedOnNotNull();
        }
    }
}
