/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.application.enums.AttachmentType;
import com.doruk.jooq.tables.Notifications;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "notifications",
    schema = "sample",
    indexes = {
        @Index(name = "idx_notifications_user_id", columnList = "user_id ASC"),
        @Index(name = "idx_notifications_user_unread", columnList = "user_id ASC, is_read ASC")
    }
)
public class NotificationsRecord extends UpdatableRecordImpl<NotificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.notifications.id</code>.
     */
    public NotificationsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sample.notifications.user_id</code>.
     */
    public NotificationsRecord setUserId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>sample.notifications.title</code>.
     */
    public NotificationsRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.title</code>.
     */
    @Column(name = "title", nullable = false, length = 255)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sample.notifications.message</code>.
     */
    public NotificationsRecord setMessage(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.message</code>.
     */
    @Column(name = "message", nullable = false)
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sample.notifications.icon</code>.
     */
    public NotificationsRecord setIcon(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.icon</code>.
     */
    @Column(name = "icon", length = 500)
    public String getIcon() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sample.notifications.attachment</code>.
     */
    public NotificationsRecord setAttachment(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.attachment</code>.
     */
    @Column(name = "attachment", length = 500)
    public String getAttachment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sample.notifications.attachment_type</code>.
     */
    public NotificationsRecord setAttachmentType(AttachmentType value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.attachment_type</code>.
     */
    @Column(name = "attachment_type")
    public AttachmentType getAttachmentType() {
        return (AttachmentType) get(6);
    }

    /**
     * Setter for <code>sample.notifications.is_read</code>.
     */
    public NotificationsRecord setIsRead(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.is_read</code>.
     */
    @Column(name = "is_read")
    public Boolean getIsRead() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>sample.notifications.created_at</code>.
     */
    public NotificationsRecord setCreatedAt(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>sample.notifications.updated_at</code>.
     */
    public NotificationsRecord setUpdatedAt(OffsetDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>sample.notifications.updated_at</code>.
     */
    @Column(name = "updated_at", precision = 6)
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationsRecord
     */
    public NotificationsRecord() {
        super(Notifications.NOTIFICATIONS);
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(Long id, UUID userId, String title, String message, String icon, String attachment, AttachmentType attachmentType, Boolean isRead, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Notifications.NOTIFICATIONS);

        setId(id);
        setUserId(userId);
        setTitle(title);
        setMessage(message);
        setIcon(icon);
        setAttachment(attachment);
        setAttachmentType(attachmentType);
        setIsRead(isRead);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(com.doruk.jooq.tables.pojos.Notifications value) {
        super(Notifications.NOTIFICATIONS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setTitle(value.getTitle());
            setMessage(value.getMessage());
            setIcon(value.getIcon());
            setAttachment(value.getAttachment());
            setAttachmentType(value.getAttachmentType());
            setIsRead(value.getIsRead());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
