/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.jooq.tables.RolePermissions;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "role_permissions",
    schema = "sample"
)
public class RolePermissionsRecord extends UpdatableRecordImpl<RolePermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.role_permissions.role_name</code>.
     */
    public RolePermissionsRecord setRoleName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.role_permissions.role_name</code>.
     */
    @Column(name = "role_name", nullable = false, length = 100)
    public String getRoleName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sample.role_permissions.permission_name</code>.
     */
    public RolePermissionsRecord setPermissionName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.role_permissions.permission_name</code>.
     */
    @Column(name = "permission_name", nullable = false, length = 200)
    public String getPermissionName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePermissionsRecord
     */
    public RolePermissionsRecord() {
        super(RolePermissions.ROLE_PERMISSIONS);
    }

    /**
     * Create a detached, initialised RolePermissionsRecord
     */
    public RolePermissionsRecord(String roleName, String permissionName) {
        super(RolePermissions.ROLE_PERMISSIONS);

        setRoleName(roleName);
        setPermissionName(permissionName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RolePermissionsRecord
     */
    public RolePermissionsRecord(com.doruk.jooq.tables.pojos.RolePermissions value) {
        super(RolePermissions.ROLE_PERMISSIONS);

        if (value != null) {
            setRoleName(value.getRoleName());
            setPermissionName(value.getPermissionName());
            resetTouchedOnNotNull();
        }
    }
}
