/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.jooq.tables.Roles;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "roles",
    schema = "sample"
)
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.roles.name</code>.
     */
    public RolesRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.roles.name</code>.
     */
    @Id
    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sample.roles.deleted_at</code>.
     */
    public RolesRecord setDeletedAt(OffsetDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.roles.deleted_at</code>.
     */
    @Column(name = "deleted_at", precision = 6)
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(String name, OffsetDateTime deletedAt) {
        super(Roles.ROLES);

        setName(name);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(com.doruk.jooq.tables.pojos.Roles value) {
        super(Roles.ROLES);

        if (value != null) {
            setName(value.getName());
            setDeletedAt(value.getDeletedAt());
            resetTouchedOnNotNull();
        }
    }
}
