/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.jooq.tables.Sessions;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "sessions",
    schema = "sample",
    uniqueConstraints = {
        @UniqueConstraint(name = "sessions_session_id_key", columnNames = { "session_id" })
    },
    indexes = {
        @Index(name = "idx_sessions_active_devices", columnList = "user_id ASC, expires_at ASC"),
        @Index(name = "idx_sessions_user_device", unique = true, columnList = "user_id ASC, device_id ASC"),
        @Index(name = "idx_sessions_user_id", columnList = "user_id ASC")
    }
)
public class SessionsRecord extends UpdatableRecordImpl<SessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.sessions.id</code>.
     */
    public SessionsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sample.sessions.user_id</code>.
     */
    public SessionsRecord setUserId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>sample.sessions.session_id</code>.
     */
    public SessionsRecord setSessionId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.session_id</code>.
     */
    @Column(name = "session_id", nullable = false, length = 255)
    public String getSessionId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sample.sessions.device_info</code>.
     */
    public SessionsRecord setDeviceInfo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.device_info</code>.
     */
    @Column(name = "device_info", length = 500)
    public String getDeviceInfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sample.sessions.device_id</code>.
     */
    public SessionsRecord setDeviceId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.device_id</code>.
     */
    @Column(name = "device_id", length = 255)
    public String getDeviceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sample.sessions.expires_at</code>.
     */
    public SessionsRecord setExpiresAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.expires_at</code>.
     */
    @Column(name = "expires_at", nullable = false, precision = 6)
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>sample.sessions.created_at</code>.
     */
    public SessionsRecord setCreatedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>sample.sessions.permissions</code>.
     */
    public SessionsRecord setPermissions(Integer[] value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sample.sessions.permissions</code>.
     */
    @Column(name = "permissions", nullable = false)
    public Integer[] getPermissions() {
        return (Integer[]) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionsRecord
     */
    public SessionsRecord() {
        super(Sessions.SESSIONS);
    }

    /**
     * Create a detached, initialised SessionsRecord
     */
    public SessionsRecord(Long id, UUID userId, String sessionId, String deviceInfo, String deviceId, OffsetDateTime expiresAt, OffsetDateTime createdAt, Integer[] permissions) {
        super(Sessions.SESSIONS);

        setId(id);
        setUserId(userId);
        setSessionId(sessionId);
        setDeviceInfo(deviceInfo);
        setDeviceId(deviceId);
        setExpiresAt(expiresAt);
        setCreatedAt(createdAt);
        setPermissions(permissions);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SessionsRecord
     */
    public SessionsRecord(com.doruk.jooq.tables.pojos.Sessions value) {
        super(Sessions.SESSIONS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setSessionId(value.getSessionId());
            setDeviceInfo(value.getDeviceInfo());
            setDeviceId(value.getDeviceId());
            setExpiresAt(value.getExpiresAt());
            setCreatedAt(value.getCreatedAt());
            setPermissions(value.getPermissions());
            resetTouchedOnNotNull();
        }
    }
}
