/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.domain.shared.enums.MultiAuthType;
import com.doruk.domain.shared.enums.UserAccountStatus;
import com.doruk.jooq.tables.Users;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "users",
    schema = "sample",
    uniqueConstraints = {
        @UniqueConstraint(name = "users_email_key", columnNames = { "email" }),
        @UniqueConstraint(name = "users_google_sub_key", columnNames = { "google_sub" }),
        @UniqueConstraint(name = "users_username_key", columnNames = { "username" })
    }
)
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.users.id</code>.
     */
    public UsersRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>sample.users.google_sub</code>.
     */
    public UsersRecord setGoogleSub(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.google_sub</code>.
     */
    @Column(name = "google_sub", length = 255)
    public String getGoogleSub() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sample.users.username</code>.
     */
    public UsersRecord setUsername(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.username</code>.
     */
    @Column(name = "username", length = 255)
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sample.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.email</code>.
     */
    @Column(name = "email", nullable = false, length = 255)
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sample.users.phone</code>.
     */
    public UsersRecord setPhone(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.phone</code>.
     */
    @Column(name = "phone", length = 255)
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sample.users.password</code>.
     */
    public UsersRecord setPassword(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.password</code>.
     */
    @Column(name = "password", length = 1024)
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sample.users.multi_factor_auth</code>.
     */
    public UsersRecord setMultiFactorAuth(MultiAuthType value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.multi_factor_auth</code>.
     */
    @Column(name = "multi_factor_auth")
    public MultiAuthType getMultiFactorAuth() {
        return (MultiAuthType) get(6);
    }

    /**
     * Setter for <code>sample.users.is_email_verified</code>.
     */
    public UsersRecord setIsEmailVerified(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.is_email_verified</code>.
     */
    @Column(name = "is_email_verified")
    public Boolean getIsEmailVerified() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>sample.users.is_phone_verified</code>.
     */
    public UsersRecord setIsPhoneVerified(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.is_phone_verified</code>.
     */
    @Column(name = "is_phone_verified")
    public Boolean getIsPhoneVerified() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>sample.users.status</code>.
     */
    public UsersRecord setStatus(UserAccountStatus value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.status</code>.
     */
    @Column(name = "status")
    public UserAccountStatus getStatus() {
        return (UserAccountStatus) get(9);
    }

    /**
     * Setter for <code>sample.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(OffsetDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>sample.users.updated_at</code>.
     */
    public UsersRecord setUpdatedAt(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>sample.users.updated_at</code>.
     */
    @Column(name = "updated_at", precision = 6)
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(UUID id, String googleSub, String username, String email, String phone, String password, MultiAuthType multiFactorAuth, Boolean isEmailVerified, Boolean isPhoneVerified, UserAccountStatus status, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Users.USERS);

        setId(id);
        setGoogleSub(googleSub);
        setUsername(username);
        setEmail(email);
        setPhone(phone);
        setPassword(password);
        setMultiFactorAuth(multiFactorAuth);
        setIsEmailVerified(isEmailVerified);
        setIsPhoneVerified(isPhoneVerified);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(com.doruk.jooq.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setGoogleSub(value.getGoogleSub());
            setUsername(value.getUsername());
            setEmail(value.getEmail());
            setPhone(value.getPhone());
            setPassword(value.getPassword());
            setMultiFactorAuth(value.getMultiFactorAuth());
            setIsEmailVerified(value.getIsEmailVerified());
            setIsPhoneVerified(value.getIsPhoneVerified());
            setStatus(value.getStatus());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
