/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.records;


import com.doruk.jooq.tables.UserDevices;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_devices",
    schema = "sample",
    indexes = {
        @Index(name = "idx_user_devices_notif_unique", unique = true, columnList = "user_id ASC, notification_device_id ASC"),
        @Index(name = "idx_user_devices_user_id", columnList = "user_id ASC")
    }
)
public class UserDevicesRecord extends UpdatableRecordImpl<UserDevicesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sample.user_devices.id</code>.
     */
    public UserDevicesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample.user_devices.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sample.user_devices.user_id</code>.
     */
    public UserDevicesRecord setUserId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample.user_devices.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>sample.user_devices.notification_device_id</code>.
     */
    public UserDevicesRecord setNotificationDeviceId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sample.user_devices.notification_device_id</code>.
     */
    @Column(name = "notification_device_id", length = 255)
    public String getNotificationDeviceId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sample.user_devices.bio_device_id</code>.
     */
    public UserDevicesRecord setBioDeviceId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sample.user_devices.bio_device_id</code>.
     */
    @Column(name = "bio_device_id", length = 255)
    public String getBioDeviceId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sample.user_devices.device_info</code>.
     */
    public UserDevicesRecord setDeviceInfo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sample.user_devices.device_info</code>.
     */
    @Column(name = "device_info", length = 500)
    public String getDeviceInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sample.user_devices.last_login_at</code>.
     */
    public UserDevicesRecord setLastLoginAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sample.user_devices.last_login_at</code>.
     */
    @Column(name = "last_login_at", precision = 6)
    public OffsetDateTime getLastLoginAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>sample.user_devices.created_at</code>.
     */
    public UserDevicesRecord setCreatedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sample.user_devices.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDevicesRecord
     */
    public UserDevicesRecord() {
        super(UserDevices.USER_DEVICES);
    }

    /**
     * Create a detached, initialised UserDevicesRecord
     */
    public UserDevicesRecord(Long id, UUID userId, String notificationDeviceId, String bioDeviceId, String deviceInfo, OffsetDateTime lastLoginAt, OffsetDateTime createdAt) {
        super(UserDevices.USER_DEVICES);

        setId(id);
        setUserId(userId);
        setNotificationDeviceId(notificationDeviceId);
        setBioDeviceId(bioDeviceId);
        setDeviceInfo(deviceInfo);
        setLastLoginAt(lastLoginAt);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserDevicesRecord
     */
    public UserDevicesRecord(com.doruk.jooq.tables.pojos.UserDevices value) {
        super(UserDevices.USER_DEVICES);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setNotificationDeviceId(value.getNotificationDeviceId());
            setBioDeviceId(value.getBioDeviceId());
            setDeviceInfo(value.getDeviceInfo());
            setLastLoginAt(value.getLastLoginAt());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
