/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq;


import com.doruk.jooq.tables.Biometrics;
import com.doruk.jooq.tables.Notifications;
import com.doruk.jooq.tables.Sessions;
import com.doruk.jooq.tables.UserDevices;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in sample.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_BIOMETRICS_USER_ID = Internal.createIndex(DSL.name("idx_biometrics_user_id"), Biometrics.BIOMETRICS, new OrderField[] { Biometrics.BIOMETRICS.USER_ID }, false);
    public static final Index IDX_NOTIFICATIONS_USER_ID = Internal.createIndex(DSL.name("idx_notifications_user_id"), Notifications.NOTIFICATIONS, new OrderField[] { Notifications.NOTIFICATIONS.USER_ID }, false);
    public static final Index IDX_NOTIFICATIONS_USER_UNREAD = Internal.createIndex(DSL.name("idx_notifications_user_unread"), Notifications.NOTIFICATIONS, new OrderField[] { Notifications.NOTIFICATIONS.USER_ID, Notifications.NOTIFICATIONS.IS_READ }, false);
    public static final Index IDX_SESSIONS_ACTIVE_DEVICES = Internal.createIndex(DSL.name("idx_sessions_active_devices"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.USER_ID, Sessions.SESSIONS.EXPIRES_AT }, false);
    public static final Index IDX_SESSIONS_USER_DEVICE = Internal.createIndex(DSL.name("idx_sessions_user_device"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.USER_ID, Sessions.SESSIONS.DEVICE_ID }, true);
    public static final Index IDX_SESSIONS_USER_ID = Internal.createIndex(DSL.name("idx_sessions_user_id"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.USER_ID }, false);
    public static final Index IDX_USER_DEVICES_NOTIF_UNIQUE = Internal.createIndex(DSL.name("idx_user_devices_notif_unique"), UserDevices.USER_DEVICES, new OrderField[] { UserDevices.USER_DEVICES.USER_ID, UserDevices.USER_DEVICES.NOTIFICATION_DEVICE_ID }, true);
    public static final Index IDX_USER_DEVICES_USER_ID = Internal.createIndex(DSL.name("idx_user_devices_user_id"), UserDevices.USER_DEVICES, new OrderField[] { UserDevices.USER_DEVICES.USER_ID }, false);
}
