/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq;


import com.doruk.jooq.tables.Biometrics;
import com.doruk.jooq.tables.MediaStore;
import com.doruk.jooq.tables.Notifications;
import com.doruk.jooq.tables.Permissions;
import com.doruk.jooq.tables.RolePermissions;
import com.doruk.jooq.tables.Roles;
import com.doruk.jooq.tables.Sessions;
import com.doruk.jooq.tables.UserDevices;
import com.doruk.jooq.tables.UserProfiles;
import com.doruk.jooq.tables.UserRoles;
import com.doruk.jooq.tables.Users;
import com.doruk.jooq.tables.records.BiometricsRecord;
import com.doruk.jooq.tables.records.MediaStoreRecord;
import com.doruk.jooq.tables.records.NotificationsRecord;
import com.doruk.jooq.tables.records.PermissionsRecord;
import com.doruk.jooq.tables.records.RolePermissionsRecord;
import com.doruk.jooq.tables.records.RolesRecord;
import com.doruk.jooq.tables.records.SessionsRecord;
import com.doruk.jooq.tables.records.UserDevicesRecord;
import com.doruk.jooq.tables.records.UserProfilesRecord;
import com.doruk.jooq.tables.records.UserRolesRecord;
import com.doruk.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * sample.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BiometricsRecord> BIOMETRICS_DEVICE_ID_KEY = Internal.createUniqueKey(Biometrics.BIOMETRICS, DSL.name("biometrics_device_id_key"), new TableField[] { Biometrics.BIOMETRICS.DEVICE_ID }, true);
    public static final UniqueKey<BiometricsRecord> BIOMETRICS_PKEY = Internal.createUniqueKey(Biometrics.BIOMETRICS, DSL.name("biometrics_pkey"), new TableField[] { Biometrics.BIOMETRICS.ID }, true);
    public static final UniqueKey<BiometricsRecord> BIOMETRICS_PUBLIC_KEY_KEY = Internal.createUniqueKey(Biometrics.BIOMETRICS, DSL.name("biometrics_public_key_key"), new TableField[] { Biometrics.BIOMETRICS.PUBLIC_KEY }, true);
    public static final UniqueKey<MediaStoreRecord> MEDIA_STORE_OBJECT_KEY_KEY = Internal.createUniqueKey(MediaStore.MEDIA_STORE, DSL.name("media_store_object_key_key"), new TableField[] { MediaStore.MEDIA_STORE.OBJECT_KEY }, true);
    public static final UniqueKey<MediaStoreRecord> MEDIA_STORE_PKEY = Internal.createUniqueKey(MediaStore.MEDIA_STORE, DSL.name("media_store_pkey"), new TableField[] { MediaStore.MEDIA_STORE.ID }, true);
    public static final UniqueKey<NotificationsRecord> NOTIFICATIONS_PKEY = Internal.createUniqueKey(Notifications.NOTIFICATIONS, DSL.name("notifications_pkey"), new TableField[] { Notifications.NOTIFICATIONS.ID }, true);
    public static final UniqueKey<PermissionsRecord> PERMISSIONS_PKEY = Internal.createUniqueKey(Permissions.PERMISSIONS, DSL.name("permissions_pkey"), new TableField[] { Permissions.PERMISSIONS.NAME }, true);
    public static final UniqueKey<RolePermissionsRecord> ROLE_PERMISSIONS_PKEY = Internal.createUniqueKey(RolePermissions.ROLE_PERMISSIONS, DSL.name("role_permissions_pkey"), new TableField[] { RolePermissions.ROLE_PERMISSIONS.ROLE_NAME, RolePermissions.ROLE_PERMISSIONS.PERMISSION_NAME }, true);
    public static final UniqueKey<RolesRecord> ROLES_PKEY = Internal.createUniqueKey(Roles.ROLES, DSL.name("roles_pkey"), new TableField[] { Roles.ROLES.NAME }, true);
    public static final UniqueKey<SessionsRecord> SESSIONS_PKEY = Internal.createUniqueKey(Sessions.SESSIONS, DSL.name("sessions_pkey"), new TableField[] { Sessions.SESSIONS.ID }, true);
    public static final UniqueKey<SessionsRecord> SESSIONS_SESSION_ID_KEY = Internal.createUniqueKey(Sessions.SESSIONS, DSL.name("sessions_session_id_key"), new TableField[] { Sessions.SESSIONS.SESSION_ID }, true);
    public static final UniqueKey<UserDevicesRecord> USER_DEVICES_PKEY = Internal.createUniqueKey(UserDevices.USER_DEVICES, DSL.name("user_devices_pkey"), new TableField[] { UserDevices.USER_DEVICES.ID }, true);
    public static final UniqueKey<UserProfilesRecord> USER_PROFILES_PKEY = Internal.createUniqueKey(UserProfiles.USER_PROFILES, DSL.name("user_profiles_pkey"), new TableField[] { UserProfiles.USER_PROFILES.ID }, true);
    public static final UniqueKey<UserProfilesRecord> USER_PROFILES_USER_ID_KEY = Internal.createUniqueKey(UserProfiles.USER_PROFILES, DSL.name("user_profiles_user_id_key"), new TableField[] { UserProfiles.USER_PROFILES.USER_ID }, true);
    public static final UniqueKey<UserRolesRecord> USER_ROLES_PKEY = Internal.createUniqueKey(UserRoles.USER_ROLES, DSL.name("user_roles_pkey"), new TableField[] { UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.NAME }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_GOOGLE_SUB_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_google_sub_key"), new TableField[] { Users.USERS.GOOGLE_SUB }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BiometricsRecord, UsersRecord> BIOMETRICS__BIOMETRICS_USER_ID_FKEY = Internal.createForeignKey(Biometrics.BIOMETRICS, DSL.name("biometrics_user_id_fkey"), new TableField[] { Biometrics.BIOMETRICS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<NotificationsRecord, UsersRecord> NOTIFICATIONS__NOTIFICATIONS_USER_ID_FKEY = Internal.createForeignKey(Notifications.NOTIFICATIONS, DSL.name("notifications_user_id_fkey"), new TableField[] { Notifications.NOTIFICATIONS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<RolePermissionsRecord, PermissionsRecord> ROLE_PERMISSIONS__ROLE_PERMISSIONS_PERMISSION_NAME_FKEY = Internal.createForeignKey(RolePermissions.ROLE_PERMISSIONS, DSL.name("role_permissions_permission_name_fkey"), new TableField[] { RolePermissions.ROLE_PERMISSIONS.PERMISSION_NAME }, Keys.PERMISSIONS_PKEY, new TableField[] { Permissions.PERMISSIONS.NAME }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<RolePermissionsRecord, RolesRecord> ROLE_PERMISSIONS__ROLE_PERMISSIONS_ROLE_NAME_FKEY = Internal.createForeignKey(RolePermissions.ROLE_PERMISSIONS, DSL.name("role_permissions_role_name_fkey"), new TableField[] { RolePermissions.ROLE_PERMISSIONS.ROLE_NAME }, Keys.ROLES_PKEY, new TableField[] { Roles.ROLES.NAME }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<SessionsRecord, UsersRecord> SESSIONS__SESSIONS_USER_ID_FKEY = Internal.createForeignKey(Sessions.SESSIONS, DSL.name("sessions_user_id_fkey"), new TableField[] { Sessions.SESSIONS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserDevicesRecord, UsersRecord> USER_DEVICES__USER_DEVICES_USER_ID_FKEY = Internal.createForeignKey(UserDevices.USER_DEVICES, DSL.name("user_devices_user_id_fkey"), new TableField[] { UserDevices.USER_DEVICES.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserProfilesRecord, MediaStoreRecord> USER_PROFILES__USER_PROFILES_PROFILE_ICON_FKEY = Internal.createForeignKey(UserProfiles.USER_PROFILES, DSL.name("user_profiles_profile_icon_fkey"), new TableField[] { UserProfiles.USER_PROFILES.PROFILE_ICON }, Keys.MEDIA_STORE_PKEY, new TableField[] { MediaStore.MEDIA_STORE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserProfilesRecord, UsersRecord> USER_PROFILES__USER_PROFILES_USER_ID_FKEY = Internal.createForeignKey(UserProfiles.USER_PROFILES, DSL.name("user_profiles_user_id_fkey"), new TableField[] { UserProfiles.USER_PROFILES.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserRolesRecord, RolesRecord> USER_ROLES__USER_ROLES_NAME_FKEY = Internal.createForeignKey(UserRoles.USER_ROLES, DSL.name("user_roles_name_fkey"), new TableField[] { UserRoles.USER_ROLES.NAME }, Keys.ROLES_PKEY, new TableField[] { Roles.ROLES.NAME }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserRolesRecord, UsersRecord> USER_ROLES__USER_ROLES_USER_ID_FKEY = Internal.createForeignKey(UserRoles.USER_ROLES, DSL.name("user_roles_user_id_fkey"), new TableField[] { UserRoles.USER_ROLES.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
