/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq;


import com.doruk.jooq.tables.Biometrics;
import com.doruk.jooq.tables.MediaStore;
import com.doruk.jooq.tables.Notifications;
import com.doruk.jooq.tables.Permissions;
import com.doruk.jooq.tables.RolePermissions;
import com.doruk.jooq.tables.Roles;
import com.doruk.jooq.tables.Sessions;
import com.doruk.jooq.tables.UserDevices;
import com.doruk.jooq.tables.UserProfiles;
import com.doruk.jooq.tables.UserRoles;
import com.doruk.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sample extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sample</code>
     */
    public static final Sample SAMPLE = new Sample();

    /**
     * The table <code>sample.biometrics</code>.
     */
    public final Biometrics BIOMETRICS = Biometrics.BIOMETRICS;

    /**
     * The table <code>sample.media_store</code>.
     */
    public final MediaStore MEDIA_STORE = MediaStore.MEDIA_STORE;

    /**
     * The table <code>sample.notifications</code>.
     */
    public final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>sample.permissions</code>.
     */
    public final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>sample.role_permissions</code>.
     */
    public final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>sample.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>sample.sessions</code>.
     */
    public final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>sample.user_devices</code>.
     */
    public final UserDevices USER_DEVICES = UserDevices.USER_DEVICES;

    /**
     * The table <code>sample.user_profiles</code>.
     */
    public final UserProfiles USER_PROFILES = UserProfiles.USER_PROFILES;

    /**
     * The table <code>sample.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>sample.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Sample() {
        super(DSL.name("sample"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Biometrics.BIOMETRICS,
            MediaStore.MEDIA_STORE,
            Notifications.NOTIFICATIONS,
            Permissions.PERMISSIONS,
            RolePermissions.ROLE_PERMISSIONS,
            Roles.ROLES,
            Sessions.SESSIONS,
            UserDevices.USER_DEVICES,
            UserProfiles.USER_PROFILES,
            UserRoles.USER_ROLES,
            Users.USERS
        );
    }
}
