/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq;


import com.doruk.jooq.tables.Biometrics;
import com.doruk.jooq.tables.MediaStore;
import com.doruk.jooq.tables.Notifications;
import com.doruk.jooq.tables.Permissions;
import com.doruk.jooq.tables.RolePermissions;
import com.doruk.jooq.tables.Roles;
import com.doruk.jooq.tables.Sessions;
import com.doruk.jooq.tables.UserDevices;
import com.doruk.jooq.tables.UserProfiles;
import com.doruk.jooq.tables.UserRoles;
import com.doruk.jooq.tables.Users;


/**
 * Convenience access to all tables in sample.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>sample.biometrics</code>.
     */
    public static final Biometrics BIOMETRICS = Biometrics.BIOMETRICS;

    /**
     * The table <code>sample.media_store</code>.
     */
    public static final MediaStore MEDIA_STORE = MediaStore.MEDIA_STORE;

    /**
     * The table <code>sample.notifications</code>.
     */
    public static final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>sample.permissions</code>.
     */
    public static final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>sample.role_permissions</code>.
     */
    public static final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>sample.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>sample.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>sample.user_devices</code>.
     */
    public static final UserDevices USER_DEVICES = UserDevices.USER_DEVICES;

    /**
     * The table <code>sample.user_profiles</code>.
     */
    public static final UserProfiles USER_PROFILES = UserProfiles.USER_PROFILES;

    /**
     * The table <code>sample.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>sample.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
