name: microsample

services:
  microsample-app:
    build: .
    container_name: microsample-app
    restart: unless-stopped
    ports:
      - "${LEDGER_PORT:-9096}:9096"
    environment:
      MICRONAUT_ENVIRONMENTS: "prod,object-storage-local"
      LEDGER_PORT: "9096"
      APP_ID: ${APP_ID:-microsample-app}
      APP_URL: ${APP_URL:?APP_URL is required}
      LOG_DIR: ${LOG_DIR:?required}
      CORS_ORIGINS: ${CORS_ORIGINS:?CORS_ORIGINS is required}
      DATASOURCE_URL: "postgresql://shared-postgres:5432/sampledb"
      DATASOURCE_USERNAME: micro_infra
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD:?required}
      NATS_URL: "nats://shared-nats:4222"
      NATS_USERNAME: microsample-system-1
      NATS_PASSWORD: ${NATS_PASSWORD:?required}
      REDIS_URL: "redis://:${REDIS_PASSWORD:?required}@shared-redis:6379"
      S3_BUCKET: ${S3_BUCKET}
      CURRENT_SERVER_PRIVATE_KEY: ${CURRENT_SERVER_PRIVATE_KEY:?required}
      CURRENT_SERVER_PUBLIC_KEY: ${CURRENT_SERVER_PUBLIC_KEY:?required}
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${FIREBASE_SERVICE_ACCOUNT_JSON}
      SOCIAIR_KEY: ${SOCIAIR_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    networks:
      - shared-infra-net
    volumes:
      - uploads:/var/www/microsample
      - logs:/var/log/microsample

networks:
  shared-infra-net:
    external: true

volumes:
  uploads:
  logs: