# ==========================
# Custom Application Properties
# ==========================
app:
  name: microsample
  app-id: ${APP_ID}
  session-expiration: ${SESSION_EXPIRATION:7} # days
  image-max-size: 5242880 # 5MB
  max-in-memory-upload-kb: 100
  current-server-private-key: ${CURRENT_SERVER_PRIVATE_KEY}
  current-server-public-key: ${CURRENT_SERVER_PUBLIC_KEY}
  app-url: ${APP_URL}
  cookie-secure: true
  local-storage-dir: /var/www/microsample
  public-path-prefix: "pub"
  private-path-prefix: "drk"
  sociair-api-key: ${SOCIAIR_KEY}
  resource-api-path: "res"
  log-dir: /var/log/microsample

# ==========================
# Micronaut Framework
# ==========================
micronaut:
  application:
    name: microsample
  security:
    enabled: true
    reject-not-found: false
    redirect:
      enabled: false
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            local-signer:
              url: http://localhost:41518/.well-known/jwks.json
              cache-expiration: 3600
        claims-validators:
          audience: ${APP_ID}
          issuer: com.doruk.jwks
    authentication: bearer
    oauth2:
      clients:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          scopes:
            - email
            - profile
            - openid
          openid:
            issuer: https://accounts.google.com
          authorization:
            url: https://accounts.google.com/o/oauth2/auth
          token:
            url: https://oauth2.googleapis.com/token
          redirect-uri: "${app.app-url}/auth/oauth/google/callback"

  executors:
    cpu-executor:
      type: fixed
      n-threads: 4

  server:
    proxy:
      enabled: true
    dispatch-options-requests: true
    netty:
      use-native-transport: true
      user-forwarded-headers: true

      listeners:
        http2Listener:
          port: ${LEDGER_PORT}
      event-loops:
        default:
          prefer-native-transport: true
          transport: io_uring
          loom-carrier: true
      event-loop-shutdown-quiet-period: 0ms
      event-loop-shutdown-timeout: 0ms

    thread-selection: blocking
    multipart:
      threshold: 102400
      mixed: true

  http:
    client:
      event-loop-group: default
      pool:
        connection-locality: enforced_if_same_group
    services:
      jwks:
        url: http://localhost:41518
        event-loop-group: default
      brevo:
        url: ${brevo.url}
        event-loop-group: default
      sociair:
        url: https://sms.sociair.com
        event-loop-group: default

# ==========================
# Infrastructure — Shared
# ==========================

jimmer:
  dialect: postgres

flyway:
  datasources:
    default:
      enabled: true
      validate-on-migrate: true
      baseline-on-migrate: true
      baseline-description: "Initial migration"
      out-of-order: false
      locations: classpath:db/migration

brevo:
  url: https://api.brevo.com
  apiKey: ${BREVO_API_KEY}
  senderEmail: ${BREVO_SENDER_EMAIL}
  senderName: ${BREVO_SENDER_NAME}

firebase:
  service-account-json: ${FIREBASE_SERVICE_ACCOUNT_JSON}

storage:
  s3:
    region: auto
    endpoint: https://<account-id>.r2.cloudflarestorage.com

kind: Application
