/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.enums;


import com.doruk.jooq.Sample;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum AttachmentType implements EnumType {

    IMAGE("IMAGE"),

    AUDIO("AUDIO"),

    VIDEO("VIDEO"),

    DOCUMENT("DOCUMENT");

    private final String literal;

    private AttachmentType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Sample.SAMPLE;
    }

    @Override
    public String getName() {
        return "attachment_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static AttachmentType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AttachmentType.class, literal);
    }
}
