/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.pojos;


import com.doruk.application.enums.AttachmentType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "notifications",
    schema = "sample",
    indexes = {
        @Index(name = "idx_notifications_user_id", columnList = "user_id ASC"),
        @Index(name = "idx_notifications_user_unread", columnList = "user_id ASC, is_read ASC")
    }
)
public class Notifications implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final UUID userId;
    private final String title;
    private final String message;
    private final String icon;
    private final String attachment;
    private final AttachmentType attachmentType;
    private final Boolean isRead;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime updatedAt;

    public Notifications(Notifications value) {
        this.id = value.id;
        this.userId = value.userId;
        this.title = value.title;
        this.message = value.message;
        this.icon = value.icon;
        this.attachment = value.attachment;
        this.attachmentType = value.attachmentType;
        this.isRead = value.isRead;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Notifications(
        Long id,
        UUID userId,
        String title,
        String message,
        String icon,
        String attachment,
        AttachmentType attachmentType,
        Boolean isRead,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.message = message;
        this.icon = icon;
        this.attachment = attachment;
        this.attachmentType = attachmentType;
        this.isRead = isRead;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>sample.notifications.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>sample.notifications.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>sample.notifications.title</code>.
     */
    @Column(name = "title", nullable = false, length = 255)
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>sample.notifications.message</code>.
     */
    @Column(name = "message", nullable = false)
    public String getMessage() {
        return this.message;
    }

    /**
     * Getter for <code>sample.notifications.icon</code>.
     */
    @Column(name = "icon", length = 500)
    public String getIcon() {
        return this.icon;
    }

    /**
     * Getter for <code>sample.notifications.attachment</code>.
     */
    @Column(name = "attachment", length = 500)
    public String getAttachment() {
        return this.attachment;
    }

    /**
     * Getter for <code>sample.notifications.attachment_type</code>.
     */
    @Column(name = "attachment_type")
    public AttachmentType getAttachmentType() {
        return this.attachmentType;
    }

    /**
     * Getter for <code>sample.notifications.is_read</code>.
     */
    @Column(name = "is_read")
    public Boolean getIsRead() {
        return this.isRead;
    }

    /**
     * Getter for <code>sample.notifications.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>sample.notifications.updated_at</code>.
     */
    @Column(name = "updated_at", precision = 6)
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Notifications other = (Notifications) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.message == null) {
            if (other.message != null)
                return false;
        }
        else if (!this.message.equals(other.message))
            return false;
        if (this.icon == null) {
            if (other.icon != null)
                return false;
        }
        else if (!this.icon.equals(other.icon))
            return false;
        if (this.attachment == null) {
            if (other.attachment != null)
                return false;
        }
        else if (!this.attachment.equals(other.attachment))
            return false;
        if (this.attachmentType == null) {
            if (other.attachmentType != null)
                return false;
        }
        else if (!this.attachmentType.equals(other.attachmentType))
            return false;
        if (this.isRead == null) {
            if (other.isRead != null)
                return false;
        }
        else if (!this.isRead.equals(other.isRead))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.message == null) ? 0 : this.message.hashCode());
        result = prime * result + ((this.icon == null) ? 0 : this.icon.hashCode());
        result = prime * result + ((this.attachment == null) ? 0 : this.attachment.hashCode());
        result = prime * result + ((this.attachmentType == null) ? 0 : this.attachmentType.hashCode());
        result = prime * result + ((this.isRead == null) ? 0 : this.isRead.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notifications (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(title);
        sb.append(", ").append(message);
        sb.append(", ").append(icon);
        sb.append(", ").append(attachment);
        sb.append(", ").append(attachmentType);
        sb.append(", ").append(isRead);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
