/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "role_permissions",
    schema = "sample"
)
public class RolePermissions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String roleName;
    private final String permissionName;

    public RolePermissions(RolePermissions value) {
        this.roleName = value.roleName;
        this.permissionName = value.permissionName;
    }

    public RolePermissions(
        String roleName,
        String permissionName
    ) {
        this.roleName = roleName;
        this.permissionName = permissionName;
    }

    /**
     * Getter for <code>sample.role_permissions.role_name</code>.
     */
    @Column(name = "role_name", nullable = false, length = 100)
    public String getRoleName() {
        return this.roleName;
    }

    /**
     * Getter for <code>sample.role_permissions.permission_name</code>.
     */
    @Column(name = "permission_name", nullable = false, length = 200)
    public String getPermissionName() {
        return this.permissionName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RolePermissions other = (RolePermissions) obj;
        if (this.roleName == null) {
            if (other.roleName != null)
                return false;
        }
        else if (!this.roleName.equals(other.roleName))
            return false;
        if (this.permissionName == null) {
            if (other.permissionName != null)
                return false;
        }
        else if (!this.permissionName.equals(other.permissionName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.roleName == null) ? 0 : this.roleName.hashCode());
        result = prime * result + ((this.permissionName == null) ? 0 : this.permissionName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RolePermissions (");

        sb.append(roleName);
        sb.append(", ").append(permissionName);

        sb.append(")");
        return sb.toString();
    }
}
