/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "sessions",
    schema = "sample",
    uniqueConstraints = {
        @UniqueConstraint(name = "sessions_session_id_key", columnNames = { "session_id" })
    },
    indexes = {
        @Index(name = "idx_sessions_active_devices", columnList = "user_id ASC, expires_at ASC"),
        @Index(name = "idx_sessions_user_device", unique = true, columnList = "user_id ASC, device_id ASC"),
        @Index(name = "idx_sessions_user_id", columnList = "user_id ASC")
    }
)
public class Sessions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final UUID userId;
    private final String sessionId;
    private final String deviceInfo;
    private final String deviceId;
    private final OffsetDateTime expiresAt;
    private final OffsetDateTime createdAt;
    private final Integer[] permissions;

    public Sessions(Sessions value) {
        this.id = value.id;
        this.userId = value.userId;
        this.sessionId = value.sessionId;
        this.deviceInfo = value.deviceInfo;
        this.deviceId = value.deviceId;
        this.expiresAt = value.expiresAt;
        this.createdAt = value.createdAt;
        this.permissions = value.permissions;
    }

    public Sessions(
        Long id,
        UUID userId,
        String sessionId,
        String deviceInfo,
        String deviceId,
        OffsetDateTime expiresAt,
        OffsetDateTime createdAt,
        Integer[] permissions
    ) {
        this.id = id;
        this.userId = userId;
        this.sessionId = sessionId;
        this.deviceInfo = deviceInfo;
        this.deviceId = deviceId;
        this.expiresAt = expiresAt;
        this.createdAt = createdAt;
        this.permissions = permissions;
    }

    /**
     * Getter for <code>sample.sessions.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>sample.sessions.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>sample.sessions.session_id</code>.
     */
    @Column(name = "session_id", nullable = false, length = 255)
    public String getSessionId() {
        return this.sessionId;
    }

    /**
     * Getter for <code>sample.sessions.device_info</code>.
     */
    @Column(name = "device_info", length = 500)
    public String getDeviceInfo() {
        return this.deviceInfo;
    }

    /**
     * Getter for <code>sample.sessions.device_id</code>.
     */
    @Column(name = "device_id", length = 255)
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Getter for <code>sample.sessions.expires_at</code>.
     */
    @Column(name = "expires_at", nullable = false, precision = 6)
    public OffsetDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Getter for <code>sample.sessions.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>sample.sessions.permissions</code>.
     */
    @Column(name = "permissions", nullable = false)
    public Integer[] getPermissions() {
        return this.permissions;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sessions other = (Sessions) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.sessionId == null) {
            if (other.sessionId != null)
                return false;
        }
        else if (!this.sessionId.equals(other.sessionId))
            return false;
        if (this.deviceInfo == null) {
            if (other.deviceInfo != null)
                return false;
        }
        else if (!this.deviceInfo.equals(other.deviceInfo))
            return false;
        if (this.deviceId == null) {
            if (other.deviceId != null)
                return false;
        }
        else if (!this.deviceId.equals(other.deviceId))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.permissions == null) {
            if (other.permissions != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.permissions, other.permissions))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.sessionId == null) ? 0 : this.sessionId.hashCode());
        result = prime * result + ((this.deviceInfo == null) ? 0 : this.deviceInfo.hashCode());
        result = prime * result + ((this.deviceId == null) ? 0 : this.deviceId.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.permissions == null) ? 0 : Arrays.deepHashCode(this.permissions));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sessions (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(sessionId);
        sb.append(", ").append(deviceInfo);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(Arrays.deepToString(permissions));

        sb.append(")");
        return sb.toString();
    }
}
