/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.pojos;


import com.doruk.domain.shared.enums.MultiAuthType;
import com.doruk.domain.shared.enums.UserAccountStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "users",
    schema = "sample",
    uniqueConstraints = {
        @UniqueConstraint(name = "users_email_key", columnNames = { "email" }),
        @UniqueConstraint(name = "users_google_sub_key", columnNames = { "google_sub" }),
        @UniqueConstraint(name = "users_username_key", columnNames = { "username" })
    }
)
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID id;
    private final String googleSub;
    private final String username;
    private final String email;
    private final String phone;
    private final String password;
    private final MultiAuthType multiFactorAuth;
    private final Boolean isEmailVerified;
    private final Boolean isPhoneVerified;
    private final UserAccountStatus status;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime updatedAt;

    public Users(Users value) {
        this.id = value.id;
        this.googleSub = value.googleSub;
        this.username = value.username;
        this.email = value.email;
        this.phone = value.phone;
        this.password = value.password;
        this.multiFactorAuth = value.multiFactorAuth;
        this.isEmailVerified = value.isEmailVerified;
        this.isPhoneVerified = value.isPhoneVerified;
        this.status = value.status;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Users(
        UUID id,
        String googleSub,
        String username,
        String email,
        String phone,
        String password,
        MultiAuthType multiFactorAuth,
        Boolean isEmailVerified,
        Boolean isPhoneVerified,
        UserAccountStatus status,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.googleSub = googleSub;
        this.username = username;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.multiFactorAuth = multiFactorAuth;
        this.isEmailVerified = isEmailVerified;
        this.isPhoneVerified = isPhoneVerified;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>sample.users.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public UUID getId() {
        return this.id;
    }

    /**
     * Getter for <code>sample.users.google_sub</code>.
     */
    @Column(name = "google_sub", length = 255)
    public String getGoogleSub() {
        return this.googleSub;
    }

    /**
     * Getter for <code>sample.users.username</code>.
     */
    @Column(name = "username", length = 255)
    public String getUsername() {
        return this.username;
    }

    /**
     * Getter for <code>sample.users.email</code>.
     */
    @Column(name = "email", nullable = false, length = 255)
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>sample.users.phone</code>.
     */
    @Column(name = "phone", length = 255)
    public String getPhone() {
        return this.phone;
    }

    /**
     * Getter for <code>sample.users.password</code>.
     */
    @Column(name = "password", length = 1024)
    public String getPassword() {
        return this.password;
    }

    /**
     * Getter for <code>sample.users.multi_factor_auth</code>.
     */
    @Column(name = "multi_factor_auth")
    public MultiAuthType getMultiFactorAuth() {
        return this.multiFactorAuth;
    }

    /**
     * Getter for <code>sample.users.is_email_verified</code>.
     */
    @Column(name = "is_email_verified")
    public Boolean getIsEmailVerified() {
        return this.isEmailVerified;
    }

    /**
     * Getter for <code>sample.users.is_phone_verified</code>.
     */
    @Column(name = "is_phone_verified")
    public Boolean getIsPhoneVerified() {
        return this.isPhoneVerified;
    }

    /**
     * Getter for <code>sample.users.status</code>.
     */
    @Column(name = "status")
    public UserAccountStatus getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>sample.users.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>sample.users.updated_at</code>.
     */
    @Column(name = "updated_at", precision = 6)
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.googleSub == null) {
            if (other.googleSub != null)
                return false;
        }
        else if (!this.googleSub.equals(other.googleSub))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.multiFactorAuth == null) {
            if (other.multiFactorAuth != null)
                return false;
        }
        else if (!this.multiFactorAuth.equals(other.multiFactorAuth))
            return false;
        if (this.isEmailVerified == null) {
            if (other.isEmailVerified != null)
                return false;
        }
        else if (!this.isEmailVerified.equals(other.isEmailVerified))
            return false;
        if (this.isPhoneVerified == null) {
            if (other.isPhoneVerified != null)
                return false;
        }
        else if (!this.isPhoneVerified.equals(other.isPhoneVerified))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.googleSub == null) ? 0 : this.googleSub.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.multiFactorAuth == null) ? 0 : this.multiFactorAuth.hashCode());
        result = prime * result + ((this.isEmailVerified == null) ? 0 : this.isEmailVerified.hashCode());
        result = prime * result + ((this.isPhoneVerified == null) ? 0 : this.isPhoneVerified.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(googleSub);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(password);
        sb.append(", ").append(multiFactorAuth);
        sb.append(", ").append(isEmailVerified);
        sb.append(", ").append(isPhoneVerified);
        sb.append(", ").append(status);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
