/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_profiles",
    schema = "sample",
    uniqueConstraints = {
        @UniqueConstraint(name = "user_profiles_user_id_key", columnNames = { "user_id" })
    }
)
public class UserProfiles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final UUID userId;
    private final String fullName;
    private final Long profileIcon;
    private final String address;
    private final String city;
    private final String state;
    private final String country;
    private final String postalCode;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime updatedAt;

    public UserProfiles(UserProfiles value) {
        this.id = value.id;
        this.userId = value.userId;
        this.fullName = value.fullName;
        this.profileIcon = value.profileIcon;
        this.address = value.address;
        this.city = value.city;
        this.state = value.state;
        this.country = value.country;
        this.postalCode = value.postalCode;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public UserProfiles(
        Long id,
        UUID userId,
        String fullName,
        Long profileIcon,
        String address,
        String city,
        String state,
        String country,
        String postalCode,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.fullName = fullName;
        this.profileIcon = profileIcon;
        this.address = address;
        this.city = city;
        this.state = state;
        this.country = country;
        this.postalCode = postalCode;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>sample.user_profiles.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>sample.user_profiles.user_id</code>.
     */
    @Column(name = "user_id")
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>sample.user_profiles.full_name</code>.
     */
    @Column(name = "full_name", length = 255)
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Getter for <code>sample.user_profiles.profile_icon</code>.
     */
    @Column(name = "profile_icon")
    public Long getProfileIcon() {
        return this.profileIcon;
    }

    /**
     * Getter for <code>sample.user_profiles.address</code>.
     */
    @Column(name = "address", length = 255)
    public String getAddress() {
        return this.address;
    }

    /**
     * Getter for <code>sample.user_profiles.city</code>.
     */
    @Column(name = "city", length = 255)
    public String getCity() {
        return this.city;
    }

    /**
     * Getter for <code>sample.user_profiles.state</code>.
     */
    @Column(name = "state", length = 255)
    public String getState() {
        return this.state;
    }

    /**
     * Getter for <code>sample.user_profiles.country</code>.
     */
    @Column(name = "country", length = 255)
    public String getCountry() {
        return this.country;
    }

    /**
     * Getter for <code>sample.user_profiles.postal_code</code>.
     */
    @Column(name = "postal_code", length = 255)
    public String getPostalCode() {
        return this.postalCode;
    }

    /**
     * Getter for <code>sample.user_profiles.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>sample.user_profiles.updated_at</code>.
     */
    @Column(name = "updated_at", precision = 6)
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserProfiles other = (UserProfiles) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.profileIcon == null) {
            if (other.profileIcon != null)
                return false;
        }
        else if (!this.profileIcon.equals(other.profileIcon))
            return false;
        if (this.address == null) {
            if (other.address != null)
                return false;
        }
        else if (!this.address.equals(other.address))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.country == null) {
            if (other.country != null)
                return false;
        }
        else if (!this.country.equals(other.country))
            return false;
        if (this.postalCode == null) {
            if (other.postalCode != null)
                return false;
        }
        else if (!this.postalCode.equals(other.postalCode))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.profileIcon == null) ? 0 : this.profileIcon.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.postalCode == null) ? 0 : this.postalCode.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserProfiles (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(fullName);
        sb.append(", ").append(profileIcon);
        sb.append(", ").append(address);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(country);
        sb.append(", ").append(postalCode);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
