/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_devices",
    schema = "sample",
    indexes = {
        @Index(name = "idx_user_devices_notif_unique", unique = true, columnList = "user_id ASC, notification_device_id ASC"),
        @Index(name = "idx_user_devices_user_id", columnList = "user_id ASC")
    }
)
public class UserDevices implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final UUID userId;
    private final String notificationDeviceId;
    private final String bioDeviceId;
    private final String deviceInfo;
    private final OffsetDateTime lastLoginAt;
    private final OffsetDateTime createdAt;

    public UserDevices(UserDevices value) {
        this.id = value.id;
        this.userId = value.userId;
        this.notificationDeviceId = value.notificationDeviceId;
        this.bioDeviceId = value.bioDeviceId;
        this.deviceInfo = value.deviceInfo;
        this.lastLoginAt = value.lastLoginAt;
        this.createdAt = value.createdAt;
    }

    public UserDevices(
        Long id,
        UUID userId,
        String notificationDeviceId,
        String bioDeviceId,
        String deviceInfo,
        OffsetDateTime lastLoginAt,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.userId = userId;
        this.notificationDeviceId = notificationDeviceId;
        this.bioDeviceId = bioDeviceId;
        this.deviceInfo = deviceInfo;
        this.lastLoginAt = lastLoginAt;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>sample.user_devices.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>sample.user_devices.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>sample.user_devices.notification_device_id</code>.
     */
    @Column(name = "notification_device_id", length = 255)
    public String getNotificationDeviceId() {
        return this.notificationDeviceId;
    }

    /**
     * Getter for <code>sample.user_devices.bio_device_id</code>.
     */
    @Column(name = "bio_device_id", length = 255)
    public String getBioDeviceId() {
        return this.bioDeviceId;
    }

    /**
     * Getter for <code>sample.user_devices.device_info</code>.
     */
    @Column(name = "device_info", length = 500)
    public String getDeviceInfo() {
        return this.deviceInfo;
    }

    /**
     * Getter for <code>sample.user_devices.last_login_at</code>.
     */
    @Column(name = "last_login_at", precision = 6)
    public OffsetDateTime getLastLoginAt() {
        return this.lastLoginAt;
    }

    /**
     * Getter for <code>sample.user_devices.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserDevices other = (UserDevices) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.notificationDeviceId == null) {
            if (other.notificationDeviceId != null)
                return false;
        }
        else if (!this.notificationDeviceId.equals(other.notificationDeviceId))
            return false;
        if (this.bioDeviceId == null) {
            if (other.bioDeviceId != null)
                return false;
        }
        else if (!this.bioDeviceId.equals(other.bioDeviceId))
            return false;
        if (this.deviceInfo == null) {
            if (other.deviceInfo != null)
                return false;
        }
        else if (!this.deviceInfo.equals(other.deviceInfo))
            return false;
        if (this.lastLoginAt == null) {
            if (other.lastLoginAt != null)
                return false;
        }
        else if (!this.lastLoginAt.equals(other.lastLoginAt))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.notificationDeviceId == null) ? 0 : this.notificationDeviceId.hashCode());
        result = prime * result + ((this.bioDeviceId == null) ? 0 : this.bioDeviceId.hashCode());
        result = prime * result + ((this.deviceInfo == null) ? 0 : this.deviceInfo.hashCode());
        result = prime * result + ((this.lastLoginAt == null) ? 0 : this.lastLoginAt.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDevices (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(notificationDeviceId);
        sb.append(", ").append(bioDeviceId);
        sb.append(", ").append(deviceInfo);
        sb.append(", ").append(lastLoginAt);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
