/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables;


import com.doruk.jooq.Keys;
import com.doruk.jooq.Sample;
import com.doruk.jooq.enums.FileVisibility;
import com.doruk.jooq.tables.UserProfiles.UserProfilesPath;
import com.doruk.jooq.tables.records.MediaStoreRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaStore extends TableImpl<MediaStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sample.media_store</code>
     */
    public static final MediaStore MEDIA_STORE = new MediaStore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaStoreRecord> getRecordType() {
        return MediaStoreRecord.class;
    }

    /**
     * The column <code>sample.media_store.id</code>.
     */
    public final TableField<MediaStoreRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>sample.media_store.object_key</code>.
     */
    public final TableField<MediaStoreRecord, String> OBJECT_KEY = createField(DSL.name("object_key"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sample.media_store.visibility</code>.
     */
    public final TableField<MediaStoreRecord, FileVisibility> VISIBILITY = createField(DSL.name("visibility"), SQLDataType.VARCHAR.defaultValue(DSL.field(DSL.raw("'PUBLIC'::sample.file_visibility"), SQLDataType.VARCHAR)).asEnumDataType(FileVisibility.class), this, "");

    /**
     * The column <code>sample.media_store.mime_type</code>.
     */
    public final TableField<MediaStoreRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sample.media_store.size</code>.
     */
    public final TableField<MediaStoreRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>sample.media_store.created_at</code>.
     */
    public final TableField<MediaStoreRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>sample.media_store.deleted_at</code>.
     */
    public final TableField<MediaStoreRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private MediaStore(Name alias, Table<MediaStoreRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaStore(Name alias, Table<MediaStoreRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sample.media_store</code> table reference
     */
    public MediaStore(String alias) {
        this(DSL.name(alias), MEDIA_STORE);
    }

    /**
     * Create an aliased <code>sample.media_store</code> table reference
     */
    public MediaStore(Name alias) {
        this(alias, MEDIA_STORE);
    }

    /**
     * Create a <code>sample.media_store</code> table reference
     */
    public MediaStore() {
        this(DSL.name("media_store"), null);
    }

    public <O extends Record> MediaStore(Table<O> path, ForeignKey<O, MediaStoreRecord> childPath, InverseForeignKey<O, MediaStoreRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_STORE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaStorePath extends MediaStore implements Path<MediaStoreRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaStorePath(Table<O> path, ForeignKey<O, MediaStoreRecord> childPath, InverseForeignKey<O, MediaStoreRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaStorePath(Name alias, Table<MediaStoreRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaStorePath as(String alias) {
            return new MediaStorePath(DSL.name(alias), this);
        }

        @Override
        public MediaStorePath as(Name alias) {
            return new MediaStorePath(alias, this);
        }

        @Override
        public MediaStorePath as(Table<?> alias) {
            return new MediaStorePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sample.SAMPLE;
    }

    @Override
    public UniqueKey<MediaStoreRecord> getPrimaryKey() {
        return Keys.MEDIA_STORE_PKEY;
    }

    @Override
    public List<UniqueKey<MediaStoreRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MEDIA_STORE_OBJECT_KEY_KEY);
    }

    private transient UserProfilesPath _userProfiles;

    /**
     * Get the implicit to-many join path to the
     * <code>sample.user_profiles</code> table
     */
    public UserProfilesPath userProfiles() {
        if (_userProfiles == null)
            _userProfiles = new UserProfilesPath(this, null, Keys.USER_PROFILES__USER_PROFILES_PROFILE_ICON_FKEY.getInverseKey());

        return _userProfiles;
    }

    @Override
    public MediaStore as(String alias) {
        return new MediaStore(DSL.name(alias), this);
    }

    @Override
    public MediaStore as(Name alias) {
        return new MediaStore(alias, this);
    }

    @Override
    public MediaStore as(Table<?> alias) {
        return new MediaStore(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaStore rename(String name) {
        return new MediaStore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaStore rename(Name name) {
        return new MediaStore(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaStore rename(Table<?> name) {
        return new MediaStore(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaStore where(Condition condition) {
        return new MediaStore(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaStore where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaStore where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaStore where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaStore where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaStore where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaStore where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaStore where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaStore whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaStore whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
