/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables;


import com.doruk.jooq.Indexes;
import com.doruk.jooq.Keys;
import com.doruk.jooq.Sample;
import com.doruk.jooq.enums.AttachmentType;
import com.doruk.jooq.tables.Users.UsersPath;
import com.doruk.jooq.tables.records.NotificationsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Notifications extends TableImpl<NotificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sample.notifications</code>
     */
    public static final Notifications NOTIFICATIONS = new Notifications();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationsRecord> getRecordType() {
        return NotificationsRecord.class;
    }

    /**
     * The column <code>sample.notifications.id</code>.
     */
    public final TableField<NotificationsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>sample.notifications.user_id</code>.
     */
    public final TableField<NotificationsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>sample.notifications.title</code>.
     */
    public final TableField<NotificationsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>sample.notifications.message</code>.
     */
    public final TableField<NotificationsRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>sample.notifications.icon</code>.
     */
    public final TableField<NotificationsRecord, String> ICON = createField(DSL.name("icon"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>sample.notifications.attachment</code>.
     */
    public final TableField<NotificationsRecord, String> ATTACHMENT = createField(DSL.name("attachment"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>sample.notifications.attachment_type</code>.
     */
    public final TableField<NotificationsRecord, com.doruk.application.enums.AttachmentType> ATTACHMENT_TYPE = createField(DSL.name("attachment_type"), SQLDataType.VARCHAR.asEnumDataType(AttachmentType.class), this, "", new EnumConverter<AttachmentType, com.doruk.application.enums.AttachmentType>(AttachmentType.class, com.doruk.application.enums.AttachmentType.class));

    /**
     * The column <code>sample.notifications.is_read</code>.
     */
    public final TableField<NotificationsRecord, Boolean> IS_READ = createField(DSL.name("is_read"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>sample.notifications.created_at</code>.
     */
    public final TableField<NotificationsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>sample.notifications.updated_at</code>.
     */
    public final TableField<NotificationsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Notifications(Name alias, Table<NotificationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Notifications(Name alias, Table<NotificationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sample.notifications</code> table reference
     */
    public Notifications(String alias) {
        this(DSL.name(alias), NOTIFICATIONS);
    }

    /**
     * Create an aliased <code>sample.notifications</code> table reference
     */
    public Notifications(Name alias) {
        this(alias, NOTIFICATIONS);
    }

    /**
     * Create a <code>sample.notifications</code> table reference
     */
    public Notifications() {
        this(DSL.name("notifications"), null);
    }

    public <O extends Record> Notifications(Table<O> path, ForeignKey<O, NotificationsRecord> childPath, InverseForeignKey<O, NotificationsRecord> parentPath) {
        super(path, childPath, parentPath, NOTIFICATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class NotificationsPath extends Notifications implements Path<NotificationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> NotificationsPath(Table<O> path, ForeignKey<O, NotificationsRecord> childPath, InverseForeignKey<O, NotificationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private NotificationsPath(Name alias, Table<NotificationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public NotificationsPath as(String alias) {
            return new NotificationsPath(DSL.name(alias), this);
        }

        @Override
        public NotificationsPath as(Name alias) {
            return new NotificationsPath(alias, this);
        }

        @Override
        public NotificationsPath as(Table<?> alias) {
            return new NotificationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sample.SAMPLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTIFICATIONS_USER_ID, Indexes.IDX_NOTIFICATIONS_USER_UNREAD);
    }

    @Override
    public UniqueKey<NotificationsRecord> getPrimaryKey() {
        return Keys.NOTIFICATIONS_PKEY;
    }

    @Override
    public List<ForeignKey<NotificationsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NOTIFICATIONS__NOTIFICATIONS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>sample.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.NOTIFICATIONS__NOTIFICATIONS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public Notifications as(String alias) {
        return new Notifications(DSL.name(alias), this);
    }

    @Override
    public Notifications as(Name alias) {
        return new Notifications(alias, this);
    }

    @Override
    public Notifications as(Table<?> alias) {
        return new Notifications(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Notifications rename(String name) {
        return new Notifications(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Notifications rename(Name name) {
        return new Notifications(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Notifications rename(Table<?> name) {
        return new Notifications(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Notifications where(Condition condition) {
        return new Notifications(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Notifications where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Notifications where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Notifications where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Notifications where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Notifications where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Notifications where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Notifications where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Notifications whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Notifications whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
