/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables;


import com.doruk.jooq.Keys;
import com.doruk.jooq.Sample;
import com.doruk.jooq.tables.RolePermissions.RolePermissionsPath;
import com.doruk.jooq.tables.Roles.RolesPath;
import com.doruk.jooq.tables.records.PermissionsRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Permissions extends TableImpl<PermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sample.permissions</code>
     */
    public static final Permissions PERMISSIONS = new Permissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PermissionsRecord> getRecordType() {
        return PermissionsRecord.class;
    }

    /**
     * The column <code>sample.permissions.name</code>.
     */
    public final TableField<PermissionsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>sample.permissions.deleted_at</code>.
     */
    public final TableField<PermissionsRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private Permissions(Name alias, Table<PermissionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Permissions(Name alias, Table<PermissionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sample.permissions</code> table reference
     */
    public Permissions(String alias) {
        this(DSL.name(alias), PERMISSIONS);
    }

    /**
     * Create an aliased <code>sample.permissions</code> table reference
     */
    public Permissions(Name alias) {
        this(alias, PERMISSIONS);
    }

    /**
     * Create a <code>sample.permissions</code> table reference
     */
    public Permissions() {
        this(DSL.name("permissions"), null);
    }

    public <O extends Record> Permissions(Table<O> path, ForeignKey<O, PermissionsRecord> childPath, InverseForeignKey<O, PermissionsRecord> parentPath) {
        super(path, childPath, parentPath, PERMISSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PermissionsPath extends Permissions implements Path<PermissionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PermissionsPath(Table<O> path, ForeignKey<O, PermissionsRecord> childPath, InverseForeignKey<O, PermissionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PermissionsPath(Name alias, Table<PermissionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PermissionsPath as(String alias) {
            return new PermissionsPath(DSL.name(alias), this);
        }

        @Override
        public PermissionsPath as(Name alias) {
            return new PermissionsPath(alias, this);
        }

        @Override
        public PermissionsPath as(Table<?> alias) {
            return new PermissionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sample.SAMPLE;
    }

    @Override
    public UniqueKey<PermissionsRecord> getPrimaryKey() {
        return Keys.PERMISSIONS_PKEY;
    }

    private transient RolePermissionsPath _rolePermissions;

    /**
     * Get the implicit to-many join path to the
     * <code>sample.role_permissions</code> table
     */
    public RolePermissionsPath rolePermissions() {
        if (_rolePermissions == null)
            _rolePermissions = new RolePermissionsPath(this, null, Keys.ROLE_PERMISSIONS__ROLE_PERMISSIONS_PERMISSION_NAME_FKEY.getInverseKey());

        return _rolePermissions;
    }

    /**
     * Get the implicit many-to-many join path to the <code>sample.roles</code>
     * table
     */
    public RolesPath roles() {
        return rolePermissions().roles();
    }

    @Override
    public Permissions as(String alias) {
        return new Permissions(DSL.name(alias), this);
    }

    @Override
    public Permissions as(Name alias) {
        return new Permissions(alias, this);
    }

    @Override
    public Permissions as(Table<?> alias) {
        return new Permissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Permissions rename(String name) {
        return new Permissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Permissions rename(Name name) {
        return new Permissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Permissions rename(Table<?> name) {
        return new Permissions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Condition condition) {
        return new Permissions(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
