/*
 * This file is generated by jOOQ.
 */
package com.doruk.jooq.tables;


import com.doruk.jooq.Indexes;
import com.doruk.jooq.Keys;
import com.doruk.jooq.Sample;
import com.doruk.jooq.tables.Users.UsersPath;
import com.doruk.jooq.tables.records.UserDevicesRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserDevices extends TableImpl<UserDevicesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sample.user_devices</code>
     */
    public static final UserDevices USER_DEVICES = new UserDevices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDevicesRecord> getRecordType() {
        return UserDevicesRecord.class;
    }

    /**
     * The column <code>sample.user_devices.id</code>.
     */
    public final TableField<UserDevicesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>sample.user_devices.user_id</code>.
     */
    public final TableField<UserDevicesRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>sample.user_devices.notification_device_id</code>.
     */
    public final TableField<UserDevicesRecord, String> NOTIFICATION_DEVICE_ID = createField(DSL.name("notification_device_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sample.user_devices.bio_device_id</code>.
     */
    public final TableField<UserDevicesRecord, String> BIO_DEVICE_ID = createField(DSL.name("bio_device_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sample.user_devices.device_info</code>.
     */
    public final TableField<UserDevicesRecord, String> DEVICE_INFO = createField(DSL.name("device_info"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>sample.user_devices.last_login_at</code>.
     */
    public final TableField<UserDevicesRecord, OffsetDateTime> LAST_LOGIN_AT = createField(DSL.name("last_login_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>sample.user_devices.created_at</code>.
     */
    public final TableField<UserDevicesRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private UserDevices(Name alias, Table<UserDevicesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserDevices(Name alias, Table<UserDevicesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sample.user_devices</code> table reference
     */
    public UserDevices(String alias) {
        this(DSL.name(alias), USER_DEVICES);
    }

    /**
     * Create an aliased <code>sample.user_devices</code> table reference
     */
    public UserDevices(Name alias) {
        this(alias, USER_DEVICES);
    }

    /**
     * Create a <code>sample.user_devices</code> table reference
     */
    public UserDevices() {
        this(DSL.name("user_devices"), null);
    }

    public <O extends Record> UserDevices(Table<O> path, ForeignKey<O, UserDevicesRecord> childPath, InverseForeignKey<O, UserDevicesRecord> parentPath) {
        super(path, childPath, parentPath, USER_DEVICES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserDevicesPath extends UserDevices implements Path<UserDevicesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserDevicesPath(Table<O> path, ForeignKey<O, UserDevicesRecord> childPath, InverseForeignKey<O, UserDevicesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserDevicesPath(Name alias, Table<UserDevicesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserDevicesPath as(String alias) {
            return new UserDevicesPath(DSL.name(alias), this);
        }

        @Override
        public UserDevicesPath as(Name alias) {
            return new UserDevicesPath(alias, this);
        }

        @Override
        public UserDevicesPath as(Table<?> alias) {
            return new UserDevicesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sample.SAMPLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_DEVICES_NOTIF_UNIQUE, Indexes.IDX_USER_DEVICES_USER_ID);
    }

    @Override
    public UniqueKey<UserDevicesRecord> getPrimaryKey() {
        return Keys.USER_DEVICES_PKEY;
    }

    @Override
    public List<ForeignKey<UserDevicesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_DEVICES__USER_DEVICES_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>sample.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.USER_DEVICES__USER_DEVICES_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public UserDevices as(String alias) {
        return new UserDevices(DSL.name(alias), this);
    }

    @Override
    public UserDevices as(Name alias) {
        return new UserDevices(alias, this);
    }

    @Override
    public UserDevices as(Table<?> alias) {
        return new UserDevices(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDevices rename(String name) {
        return new UserDevices(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDevices rename(Name name) {
        return new UserDevices(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDevices rename(Table<?> name) {
        return new UserDevices(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDevices where(Condition condition) {
        return new UserDevices(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDevices where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDevices where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDevices where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDevices where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDevices where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDevices where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDevices where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDevices whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDevices whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
